[build]
  base    = "client"
  publish = "/build"
  command = "npm build"

[[redirects]]
  from = "/users/login"
  to = "https://invoice-tracker-27.herokuapp.com/users/login"
  status = 200
  force = true # COMMENT: ensure that we always redirect
 
[[redirects]]
  from = "/users/register"
  to = "https://invoice-tracker-27.herokuapp.com/users/register"
  status = 200
  force = true # COMMENT: ensure that we always redirect
 



[[redirects]]
  from = "/invoice"
  to = "https://invoice-tracker-27.herokuapp.com/invoice"
  status = 200
  force = true # COMMENT: ensure that we always redirect
 