[build]
  base    = "client"
  publish = "/build"
  command = "npm build"

[[redirects]]
  from = "/"
  to = "https://invoice-tracker-27.herokuapp.com"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  headers = {X-From = "Netlify"}
  signed = "API_SIGNATURE_TOKEN"